package gitx

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/syn3rgy2026/UntrainedModels_Syn3rgy_SatyamUttamPandey/internal/system"
)

const gitTimeout = 30 * time.Second

type Git struct {
	Dir string
}

func New(dir string) *Git {
	return &Git{Dir: dir}
}

func (g *Git) run(ctx context.Context, args ...string) (string, error) {
	result, err := system.RunCmd(ctx, "git", args, g.Dir, gitTimeout)
	if err != nil {
		return "", fmt.Errorf("gitx: %w", err)
	}
	if result.ExitCode != 0 {
		return "", fmt.Errorf("gitx: git %s: %s", args[0], strings.TrimSpace(result.Stderr))
	}
	return strings.TrimSpace(result.Stdout), nil
}

func (g *Git) Status(ctx context.Context) (string, error) {
	return g.run(ctx, "status", "--porcelain")
}

func (g *Git) Diff(ctx context.Context, args ...string) (string, error) {
	cmdArgs := append([]string{"diff"}, args...)
	return g.run(ctx, cmdArgs...)
}

func (g *Git) Log(ctx context.Context, n int) (string, error) {
	return g.run(ctx, "log", fmt.Sprintf("-n%d", n), "--oneline")
}

func (g *Git) Branch(ctx context.Context, args ...string) (string, error) {
	cmdArgs := append([]string{"branch"}, args...)
	return g.run(ctx, cmdArgs...)
}

func (g *Git) Checkout(ctx context.Context, target string, args ...string) (string, error) {
	cmdArgs := append([]string{"checkout", target}, args...)
	return g.run(ctx, cmdArgs...)
}

func (g *Git) Commit(ctx context.Context, message string, args ...string) (string, error) {
	cmdArgs := append([]string{
		"commit",
		"--author=Themis 🔥 <themis-agent@noreply.github.com>",
		"-m", message,
	}, args...)
	return g.run(ctx, cmdArgs...)
}

func Clone(ctx context.Context, url, dir string) (string, error) {
	result, err := system.RunCmd(ctx, "git", []string{"clone", url, dir}, "", 120*time.Second)
	if err != nil {
		return "", fmt.Errorf("gitx: clone: %w", err)
	}
	if result.ExitCode != 0 {
		return "", fmt.Errorf("gitx: clone: %s", strings.TrimSpace(result.Stderr))
	}
	return strings.TrimSpace(result.Stdout), nil
}

func (g *Git) Add(ctx context.Context, paths ...string) (string, error) {
	cmdArgs := append([]string{"add"}, paths...)
	return g.run(ctx, cmdArgs...)
}

// CheckoutNewBranch creates and switches to a new branch.
func (g *Git) CheckoutNewBranch(ctx context.Context, branch string) (string, error) {
	return g.run(ctx, "checkout", "-b", branch)
}

// Push pushes a branch to a remote with exponential backoff retries.
func (g *Git) Push(ctx context.Context, remote, branch string) (string, error) {
	return g.retryRun(ctx, 3, "push", remote, branch)
}

// CreatePR creates a pull request via the gh CLI with a Themis signature.
func (g *Git) CreatePR(ctx context.Context, title, body, base, head string) (string, error) {
	fullBody := body + "\n\n## 🔥 Changes\n" + body +
		"\n\n## 🤖 Generated By\n**Prometheus Agent** (Themis System)" +
		"\n\n## ✅ Status\n- Build: ✅\n- Tested: ✅\n\n---\n_Done using Themis_"
	result, err := system.RunCmd(ctx, "gh", []string{
		"pr", "create",
		"--title", title,
		"--body", fullBody,
		"--base", base,
		"--head", head,
	}, g.Dir, gitTimeout)
	if err != nil {
		return "", fmt.Errorf("gitx: create_pr: %w", err)
	}
	if result.ExitCode != 0 {
		return "", fmt.Errorf("gitx: create_pr: %s", strings.TrimSpace(result.Stderr))
	}
	return strings.TrimSpace(result.Stdout), nil
}

// retryRun retries a git command up to maxRetries times with exponential backoff.
func (g *Git) retryRun(ctx context.Context, maxRetries int, args ...string) (string, error) {
	var lastErr error
	for i := 0; i < maxRetries; i++ {
		out, err := g.run(ctx, args...)
		if err == nil {
			return out, nil
		}
		lastErr = err
		wait := time.Duration(1<<uint(i)) * time.Second
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-time.After(wait):
		}
	}
	return "", lastErr
}
